name: CamisetasBasti
options:
  bundleIdPrefix: com.camisetasbasti
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
  defaultConfig: Release

targets:
  CamisetasBasti:
    type: application
    platform: iOS
    sources:
      - path: Models
      - path: Data
      - path: Services
      - path: Components
      - path: Views
      - path: Utils
      - path: CamisetasBastiApp.swift
      - path: Resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.camisetasbasti.app
        PRODUCT_NAME: Camisetas Basti
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "3"
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "2"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        SUPPORTS_MACCATALYST: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: "Q2TG5FA7M7"
        SWIFT_EMIT_LOC_STRINGS: YES
        DEVELOPMENT_ASSET_PATHS: ""
    scheme:
      testTargets:
        - CamisetasBastiTests
      gatherCoverageData: true

  CamisetasBastiTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CamisetasBastiTests
    dependencies:
      - target: CamisetasBasti
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Camisetas Basti.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Camisetas Basti"
        BUNDLE_LOADER: "$(TEST_HOST)"
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"

  CamisetasBastiUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CamisetasBastiUITests
    dependencies:
      - target: CamisetasBasti
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
